application: purple-wing
version: 1
runtime: go
api_version: go1

handlers:

- url: /ng
  static_files: index.html
  upload: index\.html

- url: /static
  static_dir: static/
  
- url: /.*
  script: _go_app